<?php
/**
 * @package     Joomla.Administrator
 * @subpackage  com_{COMPONENT_NAME}
 * @copyright   Copyright (C) 2012 Asikart. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 * @author      Generated by AKHelper - http://asikart.com
 */

// No direct access
defined('_JEXEC') or die;

jimport('joomla.application.component.view');

if (!class_exists('AKViewApi'))
{
	{COMPONENT_NAME}Loader('admin://includes/api/api.init');
}

/**
 * View for API System
 */
class {COMPONENT_NAME_UCFIRST}ViewApi extends AKViewApi
{
	/**
	 * Display the view
	 *
	 * @param  null  $tpl  Sub Template as default.
	 *
	 * @return mixed
	 */
	public function display($tpl = null)
	{
		return parent::display($tpl);
	}
}
