<?php
/**
 * @package     Joomla.Site
 * @subpackage  com_{COMPONENT_NAME}
 *
 * @copyright   Copyright (C) 2012 Asikart. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 * @author      Generated by AKHelper - http://asikart.com
 */

// no direct access
defined('_JEXEC') or die;


include_once AKPATH_COMPONENT.'/controllerform.php' ;

/**
 * {CONTROLLER_NAME_UCFIRST} controllerform class to edit item.
 *
 * @package     Joomla.Site
 * @subpackage  com_{COMPONENT_NAME} 
 */
class {COMPONENT_NAME_UCFIRST}Controller{CONTROLLER_NAME_UCFIRST} extends AKControllerForm
{
    /**
     * The URL view list variable.
     *
     * @var    string 
     */
    protected $view_list = '{CONTROLLER_NAMES}' ;
    
    /**
     * The URL view item variable.
     *
     * @var    string 
     */
    protected $view_item = '{CONTROLLER_NAME}' ;
    
    /**
     * The Component name.
     *
     * @var    string 
     */
    protected $component = '{COMPONENT_NAME}';
    
    /**
     * Constructor.
     *
     * @param   array  $config  An optional associative array of configuration settings.
     *
     * @see     JController
     * @since   11.1
     */
    
    function __construct() {
        
        $this->allow_url_params = array(
            'return'
        );
        
        $this->redirect_tasks = array(
            'save', 'cancel', 'publish', 'unpublish', 'delete'
        );
        
        parent::__construct();
    }
    
    /**
     * Function that allows child controller access to model data
     * after the data has been saved.
     *
     * @param   JModel  &$model     The data model object.
     * @param   array   $validData  The validated data.
     *
     * @return  void 
     *
     * @since   11.1
     */
    protected function postSaveHook( &$model, $validData = array())
    {
        $result = $model->postSaveHook($validData) ;
        return $result ;
    }
}