<?php
/**
 * @package     Joomla.Administrator
 * @subpackage  com_{COMPONENT_NAME}
 *
 * @copyright   Copyright (C) 2012 Asikart. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 * @author      Generated by AKHelper - http://asikart.com
 */

// no direct access
defined('_JEXEC') or die;

JForm::addFieldPath( JPATH_ADMINISTRATOR . '/components/com_{COMPONENT_NAME}/class/form/fields');
JFormHelper::loadFieldClass('itemlist');

/**
 * Supports an HTML select list of categories
 */
class JFormField{CONTROLLER_NAME_UCFIRST}_list extends JFormFieldItemlist
{
	/**
	 * The form field type.
	 *
	 * @var		string
	 * @since	1.6
	 */
	public $type = '{CONTROLLER_NAME_UCFIRST}_list';
	
	public $value ;
	
	public $name ;
	
	
	protected $view_list = '{CONTROLLER_NAMES}' ;
	
	protected $view_item = '{CONTROLLER_NAME}' ;
	
	protected $extension = 'com_{COMPONENT_NAME}' ;
}