<?php
/**
 * @package     Joomla.Administrator
 * @subpackage  com_{COMPONENT_NAME}
 *
 * @copyright   Copyright (C) 2012 Asikart. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 * @author      Generated by AKHelper - http://asikart.com
 */

// no direct access
defined('_JEXEC') or die;

/**
 * Supports a modal article picker.
 *
 * @package		Joomla.Administrator
 * @subpackage	com_content
 * @since		1.6
 */
class JFormField{CONTROLLER_NAME_UCFIRST}_Modal extends JFormFieldModal
{
	/**
	 * The form field type.
	 *
	 * @var		string
	 * @since	1.6
	 */
	protected $type = '{CONTROLLER_NAME_UCFIRST}_Modal';
	
	protected $view_list = '{CONTROLLER_NAMES}' ;
	
	protected $view_item = '{CONTROLLER_NAME}' ;
	
	protected $extension = 'com_{COMPONENT_NAME}' ;
	
}
