<?php
/**
 * @package     Joomla.Administrator
 * @subpackage  com_{COMPONENT_NAME}
 *
 * @copyright   Copyright (C) 2012 Asikart. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 * @author      Generated by AKHelper - http://asikart.com
 */

// no direct access
defined('_JEXEC') or die;

jimport('joomla.html.html');
JFormHelper::loadFieldClass('list');

/**
 * Supports an HTML select list.
 */
class JFormFieldItemlist extends JFormFieldList
{
	/**
	 * The form field type.
	 *
	 * @var		string
	 * @since	1.6
	 */
	public $type = 'Itemlist';
	
	public $value ;
	
	public $name ; 
	
	protected $view_list ;
	
	protected $view_item ;
	
	protected $extension ;
	
	protected $component ;
	
	
	
	protected function getOptions()
	{
		// Initialise variables.
		$this->setElement();
        $options = array();
        $name = (string) $this->element['name'];
		
		$db = JFactory::getDbo();
		$q = $db->getQuery(true) ;
		
		$q->select('*')
			->from('#__' . $this->component.'_'. $this->view_list )
			->where('published >= 1')
			;
		
		$db->setQuery($q);
		$items = $db->loadObjectList();
		
		$items = $items ? $items : array() ;
		
		foreach( $items as $item ):
			$item = new JObject($item);
			$options[] = JHtml::_('select.option', $item->id, $item->title );
		endforeach;
		
		// Merge any additional options in the XML definition.
        $options = array_merge(parent::getOptions(), $options);
		
		return $options;
	}
	
	
	
	/*
	 * function setElement
	 * @param 
	 */
	
	public function setElement()
	{
		$view_item = (string) $this->element['view_item'] ;
		$view_list = (string) $this->element['view_list'] ;
		$extension = (string) $this->element['extension'] ;
		
		if(!empty($view_item)){
			$this->view_item = $view_item ;
		}
		
		if(!empty($view_list)){
			$this->view_list = $view_list ;
		}
		
		if(!empty($extension)){
			$this->extension = $extension ;
		}
		
		$this->component = str_replace('com_', '', $this->extension );
	}
}