<?php
/**
 * @package     Joomla.Administrator
 * @subpackage  com_{COMPONENT_NAME}
 *
 * @copyright   Copyright (C) 2012 Asikart. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 * @author      Generated by AKHelper - http://asikart.com
 */

// no direct access
defined('_JEXEC') or die;

include_once JPath::clean( JPATH_ADMINISTRATOR . '/components/com_{COMPONENT_NAME}/class/proxy.class.php' ) ;


/**
 * {COMPONENT_NAME_UCFIRST} helper.
 */
class {COMPONENT_NAME_UCFIRST}Helper extends AKProxy
{
	/**
	 * Configure the Linkbar.
	 */
	public static function addSubmenu($vName = '')
	{		
		jimport('joomla.filesystem.folder');
		jimport('joomla.filesystem.file');
		
		if(JVERSION >= 3):
		
			JHtmlSidebar::addEntry(
				JText::_('JCATEGORY'),
				'index.php?option=com_categories&extension=com_{COMPONENT_NAME}',
				$vName == 'categories'
			);
			
			$folders = JFolder::folders(JPATH_ADMINISTRATOR.'/components/com_{COMPONENT_NAME}/views');
			
			foreach( $folders as $folder ){
				if( substr($folder, -2) == 'is' || substr($folder, -1) == 's'){
					JHtmlSidebar::addEntry(
						ucfirst($folder) . ' ' . JText::_('COM_{COMPONENT_NAME_UC}_TITLE_LIST'),
						'index.php?option=com_{COMPONENT_NAME}&view='.$folder,
						$vName == $folder
					);
				}
			}
		
		else:
			
			JSubMenuHelper::addEntry(
				JText::_('JCATEGORY'),
				'index.php?option=com_categories&extension=com_{COMPONENT_NAME}',
				$vName == 'categories'
			);
			
			$folders = JFolder::folders(JPATH_ADMINISTRATOR.'/components/com_{COMPONENT_NAME}/views');
			
			foreach( $folders as $folder ){
				if( substr($folder, -2) == 'is' || substr($folder, -1) == 's'){
					JSubMenuHelper::addEntry(
						ucfirst($folder) . ' ' . JText::_('COM_{COMPONENT_NAME_UC}_TITLE_LIST'),
						'index.php?option=com_{COMPONENT_NAME}&view='.$folder,
						$vName == $folder
					);
				}
			}
			
		endif;
		
	}
	

	/**
	 * Gets a list of the actions that can be performed.
	 *
	 * @return	JObject
	 * @since	1.6
	 */
	public static function getActions()
	{
		$user	= JFactory::getUser();
		$result	= new JObject;

		$assetName = 'com_{COMPONENT_NAME}';

		$actions = array(
			'core.admin', 
			'core.manage', 
			'core.create', 
			'core.edit', 
			'core.edit.own', 
			'core.edit.state', 
			'core.delete'
		);

		foreach ($actions as $action) {
			$result->set($action,	$user->authorise($action, $assetName));
		}

		return $result;
	}
	
	
	/*
	 * function getVersion
	 * @param 
	 */
	
	public static function getVersion()
	{
		return JVERSION ;
	}
	
	/*
	 * function show
	 * @param $data
	 */
	
	public static function show($data)
	{
		echo '<pre>'.print_r($data, 1).'</pre>' ;
	}
	
}
