<?php
/**
 * @package     Joomla.Administrator
 * @subpackage  com_{COMPONENT_NAME}
 *
 * @copyright   Copyright (C) 2012 Asikart. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 * @author      Generated by AKHelper - http://asikart.com
 */

// no direct access
defined('_JEXEC') or die;

?>
<div id="ak-panel-wrap">
	<div id="toolbar-box" class="ak-toolbar m">
		<div id="ref-title" class="fltlft">
			<?php echo JFactory::getApplication()->JComponentTitle; ?>
		</div>

		<?php echo JToolBar::getInstance('toolbar')->render('toolbar') ; ?>

		<div class="clr"></div>
	</div>
	
	<div id="element-box" class="m">
			<?php echo $this->loadInnerTemplate('default');?>
	</div>
</div>