<?php
/**
 * @package     Joomla.Administrator
 * @subpackage  com_{COMPONENT_NAME}
 *
 * @copyright   Copyright (C) 2012 Asikart. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 * @author      Generated by AKHelper - http://asikart.com
 */


// No direct access
defined('_JEXEC') or die;


class {COMPONENT_NAME_UCFIRST}HelperLang {
	
	const APT_KEY = 'AIzaSyC04nF4KXjfR2VQ0jsFm5vEd9LbyiXqbKw' ;
	
	/*
	 * function translate
	 * @param $text
	 */
	
	public static function translate($text, $SourceLan = null, $ResultLan = null, $separate = 0)
	{
		// if text too big, separate it.
		if($separate) {
			
			if(JString::strlen($text) > $separate) {
				$text = JString::str_split( $text, $separate );
			}else{
				$text = array($text) ;
			}
			
		}else{
			$text = array($text) ;
		}
		
		$result = '' ;
		
		// Do translate by google translate API.
		foreach( $text as $txt):
			$result .= self::gTranslate($txt,$SourceLan,$ResultLan) ;
		endforeach;
		
		return $result ;
	}
	
	
	public static function gTranslate ($text,$SourceLan,$ResultLan) {
		
		$url = new JURI();
		
		// for APIv2
		$url->setHost( 'https://www.googleapis.com/' );
		$url->setPath( 'language/translate/v2' ) ;
		
		$query['key'] 		= self::APT_KEY ;
		$query['q'] 		= urlencode($text) ;
		$query['source'] 	= $SourceLan ;
		$query['target'] 	= $ResultLan ;
		
		if( !$text ) return ;
		
		$url->setQuery( $query );
		$url->toString() ;
		$response =  file_get_contents( $url->toString() );
		
		$json = new JRegistry();
		$json->loadString( $response );
		
		$r =  $json->get( 'data.translations' ) ;
		
		return $r[0]->translatedText ;
	}
}


