<?php
/**
 * @package     Joomla.Administrator
 * @subpackage  com_{COMPONENT_NAME}
 *
 * @copyright   Copyright (C) 2012 Asikart. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 * @author      Generated by AKHelper - http://asikart.com
 */


// No direct access
defined('_JEXEC') or die;


class {COMPONENT_NAME_UCFIRST}HelperUri {
	
	public static function pathAddHost ( $path ) {
		
		if( !$path ) return ;
		
		// build path
	    $uri = new JURI( $path );
	    
	    if( $uri->getHost() ) return $path ;
	    
	    $uri->parse( JURI::root() );
	    $uri->setPath( $uri->getPath().$path );
	    $uri->setScheme( 'http' );
	    $uri->setQuery(null);
	    
	    return $uri->toString();
	}
	
	public static function base64( $action , $url ) {
		
		switch($action) {
			case 'encode' :
				$url = base64_encode( $url );
			break;
			
			case 'decode' :
				$url = str_replace( ' ' , '+' , $url );
				$url = base64_decode( $url );
			break;
		}
		return $url ;
	}
	
	public static function current( $hasQuery = false ) {
		if( $hasQuery )
			return JFactory::getURI()->toString();
		else
			return JURI::current();
	}
}


