<?php
/**
 * @package     Windwalker.Framework
 * @subpackage  AKComponentHelper
 *
 * @copyright   Copyright (C) 2012 Asikart. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 * @author      Generated by AKHelper - http://asikart.com
 */

 
// no direct access
defined('_JEXEC') or die;


class AKComponentHelperDb
{
	public static function getSelectList( $tables = array() , $all = true )
	{
		return AKComponentHelper::_('query.getSelectList', $tables , $all);
	}
	
	public static function mergeFilterFields( $filter_fields , $tables = array() )
	{
		return AKComponentHelper::_('query.mergeFilterFields', $filter_fields , $tables);
	}
	
}
