<?php
/**
 * @package     Joomla.Administrator
 * @subpackage  com_{COMPONENT_NAME}
 *
 * @copyright   Copyright (C) 2012 Asikart. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 * @author      Generated by AKHelper - http://asikart.com
 */

// no direct access
defined('_JEXEC') or die;

$doc 	= JFactory::getDocument();
$app 	= JFactory::getApplication();
$lang 	= JFactory::getLanguage();



// Define
// ========================================================================
define('{COMPONENT_NAME_UC}_SITE' , JPATH_COMPONENT_SITE );
define('{COMPONENT_NAME_UC}_ADMIN', JPATH_COMPONENT_ADMINISTRATOR);
define('{COMPONENT_NAME_UC}_SELF' , JPATH_COMPONENT);



// Include Helpers
// ========================================================================

// Core init, it can use by module, plugin or other component.
include_once JPath::clean( JPATH_ADMINISTRATOR . "/components/com_{COMPONENT_NAME}/includes/core.php" ) ;

// Set default option to path helper, then AKHelperPath will helpe us get admin path.
AKHelper::_('path.setOption', 'com_{COMPONENT_NAME}') ;


// Some useful settings
if( $app->isSite() ){
	
	// Include Admin language as global language.
	$lang->load('', JPATH_ADMINISTRATOR);
	$lang->load('com_{COMPONENT_NAME}', JPATH_COMPONENT_ADMINISTRATOR );
	{COMPONENT_NAME_UCFIRST}Helper::_('lang.loadAll', $lang->getTag());
	
	
	// Include Joomla! admin css
	{COMPONENT_NAME_UCFIRST}Helper::_('include.sortedStyle', 'includes/css');
	
	
	// set Base to fix toolbar anchor bug
	$doc->setBase( JFactory::getURI()->toString() );
	
}else{
	{COMPONENT_NAME_UCFIRST}Helper::_('lang.loadAll', $lang->getTag());
	{COMPONENT_NAME_UCFIRST}Helper::_('include.sortedStyle', 'includes/css');
}


// Detect version
{COMPONENT_NAME_UCFIRST}Helper::_('plugin.attachPlugins');

// Debug
define('AKDEBUG', {COMPONENT_NAME_UCFIRST}Helper::_('system.getConfig', 'system.debug')) ;

