<?php
/**
 * @package     Joomla.Administrator
 * @subpackage  com_{COMPONENT_NAME}
 * @copyright   Copyright (C) 2012 Asikart. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 * @author      Generated by AKHelper - http://asikart.com
 */

// No direct access
defined('_JEXEC') or die;

/**
 * {COMPONENT_NAME}Loader
 *
 * @param $uri
 *
 * @return mixed
 */
function {COMPONENT_NAME}Loader($uri)
{
	return {COMPONENT_NAME_UCFIRST}Helper::_('loader.import', $uri);
}
