<?php
/**
 * @package     Joomla.Administrator
 * @subpackage  com_{COMPONENT_NAME}
 *
 * @copyright   Copyright (C) 2012 Asikart. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 * @author      Generated by AKHelper - http://asikart.com
 */

// no direct access
defined('_JEXEC') or die;

$published = $this->state->get('filter.a_published');
?>

<?php if( JVERSION >= 3 ): ?>
<div class="modal hide fade" id="batchModal">
	<div class="modal-header">
		<button type="button" role="presentation" class="close" data-dismiss="modal">x</button>
		<h3><?php echo JText::_('COM_{COMPONENT_NAME_UC}_BATCH_OPTIONS');?></h3>
	</div>
<?php else: ?>
<fieldset class="batch">
	<legend><?php echo JText::_('COM_{COMPONENT_NAME_UC}_BATCH_OPTIONS');?></legend>
	
<?php endif; ?>
	
	<div class="modal-body">
	
		<p><?php echo JText::_('COM_{COMPONENT_NAME_UC}_BATCH_TIP'); ?></p>
		
		<?php if( isset($this->items[0]->a_access) ): ?>
		<div class="control-group">
			<div class="controls">
			<?php echo JHtml::_('batch.access');?>
			</div>
		</div>
		<?php endif; ?>
		
		
		<?php if( isset($this->items[0]->a_language) ): ?>
		<div class="control-group">
			<div class="controls">
			<?php echo JHtml::_('batch.language'); ?>
			</div>
		</div>
		<?php endif; ?>
		
	
		<?php if ($published >= 0) : ?>
		<div class="control-group">
			<div class="controls">
			<?php echo JHtml::_('batch.item', 'com_{COMPONENT_NAME}');?>
			</div>
		</div>
		<?php endif; ?>

	</div>
	
		
<?php if( JVERSION >= 3 ): ?>
	<div class="modal-footer">
		<button class="btn" type="button" onclick="document.id('batch-category-id').value='';document.id('batch-access').value='';document.id('batch-language-id').value=''" data-dismiss="modal">
			<?php echo JText::_('JCANCEL'); ?>
		</button>
		<button class="btn btn-primary" type="submit" onclick="Joomla.submitbutton('{CONTROLLER_NAME}.batch');">
			<?php echo JText::_('JGLOBAL_BATCH_PROCESS'); ?>
		</button>
	</div>
</div>
<?php else: ?>
	<div class="modal-footer">
		<button class="btn"  type="submit" onclick="Joomla.submitbutton('{CONTROLLER_NAME}.batch');">
			<?php echo JText::_('JGLOBAL_BATCH_PROCESS'); ?>
		</button>
		<button class="btn"  type="button" onclick="document.id('batch-category-id').value='';document.id('batch-access').value='';document.id('batch-language-id').value=''">
			<?php echo JText::_('JSEARCH_FILTER_CLEAR'); ?>
		</button>
	</div>
</fieldset>
<?php endif; ?>