<?php
/**
 * @package     Joomla.Administrator
 * @subpackage  com_{COMPONENT_NAME}
 *
 * @copyright   Copyright (C) 2012 Asikart. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 * @author      Generated by AKHelper - http://asikart.com
 */

// no direct access
defined('_JEXEC') or die;

$listOrder	= $this->state->get('list.ordering');
$listDirn	= $this->state->get('list.direction');
$saveOrder	= $listOrder == 'a.ordering';

$app 	= JFactory::getApplication() ;
$layout = JRequest::getVar('layout') ;

?>
<div id="filter-bar" class="btn-toolbar">
	<!-- Search Input -->
	
	<div class="btn-group pull-left fltlft">
		<?php
			$field = $this->filter['search']->getField('field') ;
			echo $field->label . ' ' ;
		?>
	</div>
	
	<div class="btn-group pull-left fltlft">
		<?php
			if( !$this->state->get('search.fulltext') ){
				echo $field->input ;
			}
		?>
	</div>
	
	<div class="btn-group pull-left fltlft">
		<?php 
			$index = $this->filter['search']->getField('index') ;
			echo $index->input ;
		?>
	</div>
	
	<button type="btn submit"><?php echo JText::_('JSEARCH_FILTER_SUBMIT'); ?></button>
	<button type="btn button" onclick="document.id('search_index').value='';this.form.submit();"><?php echo JText::_('JSEARCH_FILTER_CLEAR'); ?></button>
	
			
	<!-- Show Filters -->
	<?php foreach( $this->filter['filter']->getFieldset('filter') as $filter ): ?>
	<div class="fltrt">
		<?php echo $filter->input; ?>
	</div>
	<?php endforeach; ?>
	
</div>
<div class="clearfix"> </div>