<?php
/**
 * @package     Joomla.Administrator
 * @subpackage  com_{COMPONENT_NAME}
 *
 * @copyright   Copyright (C) 2012 Asikart. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 * @author      Generated by AKHelper - http://asikart.com
 */

// no direct access
defined('_JEXEC') or die;

JHtml::_('behavior.tooltip');
JHtml::_('behavior.multiselect');
{COMPONENT_NAME_UCFIRST}Helper::_('include.core');



// Init some API objects
// ================================================================================
$app 	= JFactory::getApplication() ;
$date 	= JFactory::getDate( 'now' , JFactory::getConfig()->get('offset') ) ;
$doc 	= JFactory::getDocument();
$uri 	= JFactory::getURI() ;
$user	= JFactory::getUser();
$userId	= $user->get('id');



// List Control
// ================================================================================
$listOrder	= $this->state->get('list.ordering');
$listDirn	= $this->state->get('list.direction');
$originalOrders = array();


// For Site
// ================================================================================
if($app->isSite()) {
	{COMPONENT_NAME_UCFIRST}Helper::_('include.bluestork');
	// {COMPONENT_NAME_UCFIRST}Helper::_('include.fixBootstrapToJoomla');
}

?>

<div id="{COMPONENT_NAME}-{CONTROLLER_NAMES}">

	<!-- Form Begin -->
	<form action="<?php echo JFactory::getURI()->toString(); ?>" method="post" name="adminForm" id="adminForm" enctype="multipart/form-data">
		
		
		<!-- Filter-->
		<?php echo $this->loadTemplate('filter'); ?>
	
		
		<!-- Table -->
		<?php echo $this->loadTemplate('table') ; ?>
		
		
		<!-- Batch -->
		<?php
			if( JFile::exists(JPATH_COMPONENT.'/views/{CONTROLLER_NAMES}/tmpl/default_batch.php') ){
				echo $this->loadTemplate('batch'); 
			}
		?>
		
		<!-- Hidden Inputs -->
		<div id="hidden-inputs">
			<input type="hidden" name="task" value="" />
			<input type="hidden" name="boxchecked" value="0" />
			<input type="hidden" name="filter_order" value="<?php echo $listOrder; ?>" />
			<input type="hidden" name="filter_order_Dir" value="<?php echo $listDirn; ?>" />
			<input type="hidden" name="original_order_values" value="<?php echo implode($originalOrders, ','); ?>" />
			<?php echo JHtml::_('form.token'); ?>
		</div>
	</form>

</div>