<?php
/**
 * @package     Windwalker.Framework
 * @subpackage  AKComponentHelper
 *
 * @copyright   Copyright (C) 2012 Asikart. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 * @author      Generated by AKHelper - http://asikart.com
 */

// no direct access
defined('_JEXEC') or die;

include_once JPath::clean( JPATH_ADMINISTRATOR . "/components/com_{COMPONENT_NAME}/class/componenthelper.php" ) ;
include_once JPath::clean( JPATH_ADMINISTRATOR . "/components/com_{COMPONENT_NAME}/helpers/{COMPONENT_NAME}.php" ) ;
include_once JPath::clean( JPATH_ADMINISTRATOR . "/components/com_{COMPONENT_NAME}/includes/loader.php" ) ;

// Set Default helper prefix as default
{COMPONENT_NAME_UCFIRST}Helper::setPrefix('AKComponentHelper') ;
{COMPONENT_NAME_UCFIRST}Helper::addIncludePath(JPATH_ADMINISTRATOR . '/components/com_{COMPONENT_NAME}/class/helpers');
{COMPONENT_NAME_UCFIRST}Helper::_('path.setOption', 'com_{COMPONENT_NAME}') ;

// Set Component helper prefix
{COMPONENT_NAME_UCFIRST}Helper::setPrefix('{COMPONENT_NAME_UCFIRST}Helper') ;
{COMPONENT_NAME_UCFIRST}Helper::addIncludePath(JPATH_ADMINISTRATOR . '/components/com_{COMPONENT_NAME}/helpers');