<?php
/**
 * @package     Joomla.Administrator
 * @subpackage  com_{COMPONENT_NAME}
 *
 * @copyright   Copyright (C) 2012 Asikart. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 * @author      Generated by AKHelper - http://asikart.com
 */

// no direct access
defined('_JEXEC') or die;

$doc 	= JFactory::getDocument();
$app 	= JFactory::getApplication();
$lang 	= JFactory::getLanguage();



// Define
// ========================================================================
define('{COMPONENT_NAME_UC}_SITE' , JPATH_COMPONENT_SITE );
define('{COMPONENT_NAME_UC}_ADMIN', JPATH_COMPONENT_ADMINISTRATOR);
define('{COMPONENT_NAME_UC}_SELF' , JPATH_COMPONENT);

if(!defined('DS')){
	define('DS', DIRECTORY_SEPARATOR) ;
}



// Include global helper.
include_once JPath::clean( JPATH_ADMINISTRATOR . "/components/com_{COMPONENT_NAME}/includes/core.php" ) ;



// Include joomla api
// ========================================================================
jimport('joomla.html.toolbar');
jimport('joomla.filesystem.folder');
jimport('joomla.filesystem.file');



// Include Windwalker class
// ========================================================================
{COMPONENT_NAME}Loader("admin://class/toolbar" ) ;
{COMPONENT_NAME}Loader("admin://class/text" ) ;




// Include Helpers
// ========================================================================

if( $app->isSite() ){
	
	// Include Admin language as global language.
	$lang->load('', JPATH_ADMINISTRATOR);
	$lang->load('com_{COMPONENT_NAME}', JPATH_COMPONENT_ADMINISTRATOR );
	{COMPONENT_NAME_UCFIRST}Helper::_('lang.loadAll', $lang->getTag());
	
	
	// Include Joomla! admin css
	{COMPONENT_NAME_UCFIRST}Helper::_('include.sortedStyle', 'includes/css');
	
	
	// set Base to fix toolbar anchor bug
	$doc->setBase( JFactory::getURI()->toString() );
	
}else{
	{COMPONENT_NAME_UCFIRST}Helper::_('lang.loadAll', $lang->getTag());
	{COMPONENT_NAME_UCFIRST}Helper::_('include.sortedStyle', 'includes/css');
}


// Detect version
{COMPONENT_NAME_UCFIRST}Helper::_('version.detectVersion');

