<?php
/**
 * @package     Joomla.Administrator
 * @subpackage  com_{COMPONENT_NAME}
 *
 * @copyright   Copyright (C) 2012 Asikart. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 * @author      Generated by AKHelper - http://asikart.com
 */

// no direct access
defined('_JEXEC') or die;

jimport('joomla.application.component.view');

/**
 * View class for a list of {COMPONENT_NAME_UCFIRST}.
 */
class {COMPONENT_NAME_UCFIRST}View{CONTROLLER_NAMES_UCFIRST} extends AKViewApi
{
	protected $items;
	protected $pagination;
	protected $state;
	
	public	$list_name = '{CONTROLLER_NAMES}' ;
	public	$item_name = '{CONTROLLER_NAME}' ;
	
	public	$lead_items ;
	public	$intro_items ;
	public	$link_items ;

	/**
	 * Display the view
	 */
	public function display($tpl = null)
	{
		$items = $this->get('Items') ;
		$this->setBuffer($items) ;
		
		parent::display($tpl);
	}
}
