<?php
/**
 * @package     Joomla.Administrator
 * @subpackage  com_{COMPONENT_NAME}
 *
 * @copyright   Copyright (C) 2012 Asikart. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 * @author      Generated by AKHelper - http://asikart.com
 */

// no direct access
defined('_JEXEC') or die;

include_once AKPATH_COMPONENT.'/viewitem.php' ;

/**
 * View to edit
 */
class {COMPONENT_NAME_UCFIRST}View{CONTROLLER_NAME_UCFIRST} extends AKViewItem
{
	/**
	 * @var		string	The prefix to use with controller messages.
	 * @since	1.6
	 */
	protected 	$text_prefix = 'COM_{COMPONENT_NAME_UC}';
	protected 	$items;
	protected 	$pagination;
	protected 	$state;
	
	public		$option 	= 'com_{COMPONENT_NAME}' ;
	public		$list_name 	= '{CONTROLLER_NAMES}' ;
	public		$item_name 	= '{CONTROLLER_NAME}' ;
	public		$sort_fields ;
	
	

	/**
	 * Display the view
	 */
	public function display($tpl = null)
	{
		$app = JFactory::getApplication() ;
		
		$this->state	= $this->get('State');
		$this->item		= $this->get('Item');
		$this->form		= $this->get('Form');
		$this->fields_group = $this->get('FieldsGroup');
		$this->fields	= $this->get('FieldsName');
		$this->canDo	= AKHelper::getActions($this->option);

		// Check for errors.
		if (count($errors = $this->get('Errors'))) {
			JError::raiseError(500, implode("\n", $errors));
			return false;
		}

		parent::displayWithPanel($tpl) ;
	}

	
	
	/**
	 * Add the page title and toolbar.
	 */
	protected function addToolbar()
	{
		// Set title.
		$title = AKDEV
				? ucfirst($this->getName()) . ' ' . JText::_($this->text_prefix.'_TITLE_ITEM_EDIT')
				: JText::_($this->text_prefix . '_' . strtoupper($this->getName()) . '_TITLE_ITEM_EDIT')
				;
		AKToolBarHelper::title( $title, 'article-add.png');
		
		parent::addToolbar();
	}
	
	
	
	/*
	 * function handleFields
	 * @param 
	 */
	
	public function handleFields()
	{
		$form = $this->form ;
		
		parent::handleFields();
		
		// for Joomla! 3.0
		if(JVERSION >= 3) {
			
			// $form->removeField('name', 'fields');
			
		}else{
			
			// $form->removeField('name', 'fields');
			
		}
		
	}
}
